### ISSUE TITLE
Using py-sphviewer to visualize high-dimensional data

### ISSUE THREAD

**Issue by ivan-marroquin** [alejandrobll/py-sphviewer#10]
Hi Alejandro,

I found your project very interesting. I can see that it offers plenty of opportunities to try new things. I am very interested in founding a way to use the visualization capabilities in py-sphviewer to display high-dimensional data.

At this moment, the workflow that I have in mind is: high-dimensional data -> projected to a 3d subspace using a dimensionality reduction technique -> generate a file compatible with py-sphviewer -> and produce amazing graphic displays.

Unfortunately, I am not in expert in SPH. So, I don't know what are the required components to build the required information to use py-sphviewer. At this moment, I have high-dimensional data in ASCII format.

So, I am hoping that you could guide me in this process.

I thank you in advance for the attention you pay to my request.

Ivan

**Comment by alejandrobll** [comment]
This has been addressed by private mail. I'll close the issue then.
