### ISSUE TITLE
Request: could you make available the Python code for the blending tutorial?

### ISSUE THREAD

**Issue by ivan-marroquin** [alejandrobll/py-sphviewer#12]
HI @alejandrobll ,

I am following the tutorial examples shown in the main webpage of Py-SPHViewer. Could you make available the Python code for the animated image shown at the bottom of the blending tutorial page?

It will help me to better understand how to use the camera, scene, and rotations. So then, I can follow better the instructions for the smooth camera tutorial. Also, could you make available the data to simulate gas particles, which is used for the tutorial on  blending images?

Many thanks,
Ivan

**Comment by alejandrobll** [comment]
Already replied in private email
