### ISSUE TITLE
Installation fails on Windows 7

### ISSUE THREAD

**Issue by rafael-wampfler** [alejandrobll/py-sphviewer#13]
Hello

I have tried to install py-sphviewer on Windows 7 64 bit. I'm running Python 3.7.1 with Anaconda. I'm getting the following error message. What is the problem?

C:\Users\myName>pip install py-sphviewer --user
Collecting py-sphviewer
  Using cached https://files.pythonhosted.org/packages/52/a6/bf35362179adcb8390f
fd534a9efdd86713289e0f1d9974bd159f86d296c/py-sphviewer-1.2.0.tar.gz
Requirement already satisfied: pykdtree in c:\users\myName\appdata\roaming\pyth
on\python37\site-packages (from py-sphviewer) (1.3.1)
Requirement already satisfied: numpy in c:\users\myName\appdata\local\continuum
\anaconda3\lib\site-packages (from pykdtree->py-sphviewer) (1.15.4)
Building wheels for collected packages: py-sphviewer
  Running setup.py bdist_wheel for py-sphviewer ... error
  Complete output from command C:\Users\myName\AppData\Local\Continuum\anaconda
3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\myName\\Ap
pData\\Local\\Temp\\pip-install-ycx64p33\\py-sphviewer\\setup.py';f=getattr(toke
nize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec
(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\myName\AppData\Local
\Temp\pip-wheel-9i6bx7_k --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\Camera.py -> build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\Particles.py -> build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\Render.py -> build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\Scene.py -> build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\version.py -> build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\__init__.py -> build\lib.win-amd64-3.7\sphviewer
  creating build\lib.win-amd64-3.7\sphviewer\extensions
  copying sphviewer\extensions\__init__.py -> build\lib.win-amd64-3.7\sphviewer\
extensions
  creating build\lib.win-amd64-3.7\sphviewer\tools
  copying sphviewer\tools\Blend.py -> build\lib.win-amd64-3.7\sphviewer\tools
  copying sphviewer\tools\camera_tools.py -> build\lib.win-amd64-3.7\sphviewer\t
ools
  copying sphviewer\tools\cmaps.py -> build\lib.win-amd64-3.7\sphviewer\tools
  copying sphviewer\tools\hsv_tools.py -> build\lib.win-amd64-3.7\sphviewer\tool
s
  copying sphviewer\tools\QuickView.py -> build\lib.win-amd64-3.7\sphviewer\tool
s
  copying sphviewer\tools\__init__.py -> build\lib.win-amd64-3.7\sphviewer\tools

  copying sphviewer\c_code.c -> build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\extra_code.c -> build\lib.win-amd64-3.7\sphviewer
  copying sphviewer\README.txt -> build\lib.win-amd64-3.7\sphviewer
  running build_ext
  building 'sphviewer/extensions/scene' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\sphviewer
  creating build\temp.win-amd64-3.7\Release\sphviewer\extensions
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c
 /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\myName\AppData\Local\Continuum\ana
conda3\lib\site-packages\numpy\core\include -IC:\Users\myName\AppData\Local\Con
tinuum\anaconda3\include -IC:\Users\myName\AppData\Local\Continuum\anaconda3\in
clude "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\P
rogram Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program File
s (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\
8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcsph
viewer/extensions/scenemodule.c /Fobuild\temp.win-amd64-3.7\Release\sphviewer/ex
tensions/scenemodule.obj -fopenmp -w -std=c99
  cl : Command line warning D9025 : overriding '/W3' with '/w'
  cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
  cl : Command line warning D9002 : ignoring unknown option '-std=c99'
  scenemodule.c
  c:\users\myName\appdata\local\continuum\anaconda3\lib\site-packages\numpy\cor
e\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated Num
Py API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe
/nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH
:C:\Users\myName\AppData\Local\Continuum\anaconda3\libs /LIBPATH:C:\Users\wrafa
el\AppData\Local\Continuum\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x
86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\
Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Wind
ows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit_sphviewer/extensions/scene build
\temp.win-amd64-3.7\Release\sphviewer/extensions/scenemodule.obj /OUT:build\lib.
win-amd64-3.7\sphviewer/extensions/scene.cp37-win_amd64.pyd /IMPLIB:build\temp.w
in-amd64-3.7\Release\sphviewer/extensions\scene.cp37-win_amd64.lib -lgomp
  LINK : warning LNK4044: unrecognized option '/lgomp'; ignored
  LINK : error LNK2001: unresolved external symbol PyInit_sphviewer/extensions/s
cene
  build\temp.win-amd64-3.7\Release\sphviewer/extensions\scene.cp37-win_amd64.lib
 : fatal error LNK1120: 1 unresolved externals
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN
\\x86_amd64\\link.exe' failed with exit status 1120

  ----------------------------------------
  Failed building wheel for py-sphviewer
  Running setup.py clean for py-sphviewer
Failed to build py-sphviewer
Installing collected packages: py-sphviewer
  Running setup.py install for py-sphviewer ... error
    Complete output from command C:\Users\myName\AppData\Local\Continuum\anacon
da3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\myName\\
AppData\\Local\\Temp\\pip-install-ycx64p33\\py-sphviewer\\setup.py';f=getattr(to
kenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();ex
ec(compile(code, __file__, 'exec'))" install --record C:\Users\myName\AppData\L
ocal\Temp\pip-record-aeg0kk7s\install-record.txt --single-version-externally-man
aged --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\Camera.py -> build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\Particles.py -> build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\Render.py -> build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\Scene.py -> build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\version.py -> build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\__init__.py -> build\lib.win-amd64-3.7\sphviewer
    creating build\lib.win-amd64-3.7\sphviewer\extensions
    copying sphviewer\extensions\__init__.py -> build\lib.win-amd64-3.7\sphviewe
r\extensions
    creating build\lib.win-amd64-3.7\sphviewer\tools
    copying sphviewer\tools\Blend.py -> build\lib.win-amd64-3.7\sphviewer\tools
    copying sphviewer\tools\camera_tools.py -> build\lib.win-amd64-3.7\sphviewer
\tools
    copying sphviewer\tools\cmaps.py -> build\lib.win-amd64-3.7\sphviewer\tools
    copying sphviewer\tools\hsv_tools.py -> build\lib.win-amd64-3.7\sphviewer\to
ols
    copying sphviewer\tools\QuickView.py -> build\lib.win-amd64-3.7\sphviewer\to
ols
    copying sphviewer\tools\__init__.py -> build\lib.win-amd64-3.7\sphviewer\too
ls
    copying sphviewer\c_code.c -> build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\extra_code.c -> build\lib.win-amd64-3.7\sphviewer
    copying sphviewer\README.txt -> build\lib.win-amd64-3.7\sphviewer
    running build_ext
    building 'sphviewer/extensions/scene' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\sphviewer
    creating build\temp.win-amd64-3.7\Release\sphviewer\extensions
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
/c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\myName\AppData\Local\Continuum\a
naconda3\lib\site-packages\numpy\core\include -IC:\Users\myName\AppData\Local\C
ontinuum\anaconda3\include -IC:\Users\myName\AppData\Local\Continuum\anaconda3\
include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:
\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Fi
les (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kit
s\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcs
phviewer/extensions/scenemodule.c /Fobuild\temp.win-amd64-3.7\Release\sphviewer/
extensions/scenemodule.obj -fopenmp -w -std=c99
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    scenemodule.c
    c:\users\myName\appdata\local\continuum\anaconda3\lib\site-packages\numpy\c
ore\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated N
umPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.ex
e /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPA
TH:C:\Users\myName\AppData\Local\Continuum\anaconda3\libs /LIBPATH:C:\Users\wra
fael\AppData\Local\Continuum\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files
(x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86
)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Wi
ndows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit_sphviewer/extensions/scene bui
ld\temp.win-amd64-3.7\Release\sphviewer/extensions/scenemodule.obj /OUT:build\li
b.win-amd64-3.7\sphviewer/extensions/scene.cp37-win_amd64.pyd /IMPLIB:build\temp
.win-amd64-3.7\Release\sphviewer/extensions\scene.cp37-win_amd64.lib -lgomp
    LINK : warning LNK4044: unrecognized option '/lgomp'; ignored
    LINK : error LNK2001: unresolved external symbol PyInit_sphviewer/extensions
/scene
    build\temp.win-amd64-3.7\Release\sphviewer/extensions\scene.cp37-win_amd64.l
ib : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\link.exe' failed with exit status 1120

    ----------------------------------------
Command "C:\Users\myName\AppData\Local\Continuum\anaconda3\python.exe -u -c "im
port setuptools, tokenize;__file__='C:\\Users\\myName\\AppData\\Local\\Temp\\pi
p-install-ycx64p33\\py-sphviewer\\setup.py';f=getattr(tokenize, 'open', open)(__
file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file_
_, 'exec'))" install --record C:\Users\myName\AppData\Local\Temp\pip-record-aeg
0kk7s\install-record.txt --single-version-externally-managed --compile --user --
prefix=" failed with error code 1 in C:\Users\myName\AppData\Local\Temp\pip-ins
tall-ycx64p33\py-sphviewer\

**Comment by alejandrobll** [comment]
Thanks for pointing this out. 

I think the problem is that you are compiling the code with MSVC. According to this [link](https://docs.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=vs-2019) 
you should change the -fopenmp in extra_compile_args in setup.py by /openmp. Otherwise, you could install gcc and compile the code with gcc. 

I think this has to be fixed so that we switch to the right flags when using a compiler that does not support a certain flag.

**Comment by rafael-wampfler** [comment]
Thank you very much for your answer. So you mean exchanging extra_compile_args=['-fopenmp','-w', '-std=c99', '-ffast-math'] by extra_compile_args=['-/openmp','-w', '-std=c99', '-ffast-math'] in your setup.py? Then I just have to run python setup.py install?

**Comment by alejandrobll** [comment]
Yes. Please try and report if you succeed.

**Comment by rafael-wampfler** [comment]
Alright, is it '-/openmp' or '/openmp'?

**Comment by rafael-wampfler** [comment]
Installation worked when replacing -fopenmp by -openmp.
