### ISSUE TITLE
Heat map of 3 values (x,y,z) in 2D plane

### ISSUE THREAD

**Issue by rafael-wampfler** [alejandrobll/py-sphviewer#15]
Hello

I'm using the following method to create a 2D histogram:

```
def sphviewer_plot(x, y, nb=32, xsize=500, ysize=500):   
    xmin = np.min(x)
    xmax = np.max(x)
    ymin = np.min(y)
    ymax = np.max(y)

    x0 = (xmin+xmax)/2.
    y0 = (ymin+ymax)/2.

    pos = np.zeros([len(x), 3])
    pos[:,0] = x
    pos[:,1] = y
    w = np.ones(len(x))

    P = sph.Particles(pos, w, nb=nb)
    S = sph.Scene(P)
    S.update_camera(r='infinity', x=x0, y=y0, z=0, 
                    xsize=xsize, ysize=ysize)
    R = sph.Render(S)
    R.set_logscale()
    img = R.get_image()
    extent = R.get_extent()
    for i, j in zip(range(4), [x0,x0,y0,y0]):
        extent[i] += j
    return img, extent
```

I'm creating the histogram using the following lines of code:
```

fig = plt.figure(figsize=(15,15))
ax = fig.add_subplot(111)
img, extent = sphviewer_plot(df["x"].values, df["y"].values, 16, xsize=300, ysize=300)
img = np.flipud(img)
ax.imshow(img, extent=extent, origin='lower', cmap=mycmap)
ax.set_xlim(0,1080)
ax.set_ylim(0,1920)
plt.show()
```

df is a Pandas DataFrame. This works great but now I would like to create a 2D heat map using three values x, y and z, i.e. for each pair of x and y values I have an additional value z. I could create such a heatmap by using binned_statistic_2d() as follows:

```
heatmap, xedges, yedges, binnumber = stats.binned_statistic_2d(x, y, values=z, statistic='mean', bins=1000, range=[[0, 1080], [0, 1920]])
heatmap[np.isnan(heatmap)] = 0
heatmap = gaussian_filter(heatmap, sigma=s)
```

Is it possible to adapt sphviewer_plot() to also support 3 values x and and z? Moreover, is it possible to also provide the range to the method as done in binned_statistic_2d above?

**Comment by alejandrobll** [comment]
z is the weight of your data? If so, the script that you copied from stackoverflow already includes a weight, set to one for all particles. Just include the weight as an input of the function and remove the "w" from the function. In any case, these are not issues with py-sphviewer, so I encourage you to ask them in stackoverflow. I'll close this discussion now.
