### ISSUE TITLE
Surface density error

### ISSUE THREAD

**Issue by AshKelly** [alejandrobll/py-sphviewer#16]
The surface density is dependent on both the `xsize` and `ysize` which, I believe, should just define how many pixels we use,
e.g,
```python
import h5py
from sphviewer.tools import QuickView
from pykdtree.kdtree import KDTree
import matplotlib.pyplot as plt
import numpy as np

def calculate_smoothing_lengths(coords, neigh=32):
    tree = KDTree(coords)
    d, idx = tree.query(coords, k=neigh)
    hsml = d[:, neigh - 1]
    return hsml


halo = h5py.File('dm_halo.h5py', 'r')
pos  = halo['Coordinates'].value
hsml = calculate_smoothing_lengths(pos)

qv = QuickView(pos, r='infinity', hsml=hsml, nb=8, xsize=100, ysize=100, plot=False,
               logscale=False).get_image()

qv2 = QuickView(pos, r='infinity', hsml=hsml, nb=8, xsize=500, ysize=500, plot=False,
               logscale=False).get_image()

qv3 = QuickView(pos, r='infinity', hsml=hsml, nb=8, xsize=1500, ysize=1500, plot=False,
               logscale=False).get_image()


fig, axes = plt.subplots(1, 3, figsize=(15, 5), dpi=300)

axes[0].imshow(np.log10(qv + 1e-12), vmin=0, vmax=3)
axes[1].imshow(np.log10(qv2 + 1e-12), vmin=0, vmax=3)
axes[2].imshow(np.log10(qv3 + 1e-12), vmin=0, vmax=3)

for ax in axes:
    ax.set_xticklabels([])
    ax.set_yticklabels([])

plt.tight_layout()
plt.savefig("resolution_test.png", dpi=300)
plt.show()
```

which gives

![resolution_test](https://user-images.githubusercontent.com/30047498/62354515-fcf63000-b504-11e9-9fea-4e0667ebf63f.png)

but I believe the surface density should be constant. The bug is in `rendermodule.c`

**Comment by AshKelly** [comment]
@jborrow

**Comment by JBorrow** [comment]
Would you be able to try this with the swiftsimio vis? Or your yt stuff?

**Comment by AshKelly** [comment]
Yes this doesn't happen with my stuff; also swiftsimio seems to be independent of size

**Comment by AshKelly** [comment]
In `rendermodule.c` L116 we have
`local_image[(yy+k)*xsize+(xx+j)] += mm*cubic_kernel(sqrt((float)j*(float)j+(float)k*(float)k), tt);`

where `k` and `j` are how many pixels away we in `x` and `y` directions in units of pixel size. But, `tt` is the inputted smoothing length so its in some physical units

**Comment by AshKelly** [comment]
I found this bug via comparison with my own SPH renderer

**Comment by alejandrobll** [comment]
It's not a bug. It is on purpose. You should correct by the physical area
of the pixel.

**Comment by AshKelly** [comment]
I see; I thought it did this internally. Cheers!

**Comment by MatthieuSchaller** [comment]
Isn't this related to the issue Sylvia was seeing in her column denity maps?

**Comment by AshKelly** [comment]
I've re-looked into this and what you suggested works Alejandro,


Using the following script,

```
import h5py
import sphviewer.tools
from pykdtree.kdtree import KDTree
import matplotlib.pyplot as plt
import numpy as np

from sph_utils import scatter_image


def calculate_smoothing_lengths(coords, neigh=32):
    tree = KDTree(coords)
    d, idx = tree.query(coords, k=neigh)
    hsml = d[:, neigh - 1]
    return hsml


# generating a random 1/r^2 particle dist
pos = []
for i in range(100000):
    x = np.random.uniform(0, 1)
    y = np.random.uniform(0, 1)
    
    prob = np.random.uniform(0, 1)
    
    if prob < (0.25 / ((x-0.5)**2 + (y-0.5)**2 + 0.5))**2:
        pos.append([x, y, 0.5])
pos = np.vstack(pos)

# calculating smoothing lengths
hsml = calculate_smoothing_lengths(pos)

qv = sphviewer.tools.QuickView(pos, np.ones_like(pos[:, 0]), r='infinity', hsml=hsml, xsize=100, ysize=100, plot=False, 
               logscale=False, x=0.5, y=0.5).get_image()

qv2 = sphviewer.tools.QuickView(pos, np.ones_like(pos[:, 0]), r='infinity', hsml=hsml, xsize=500, ysize=500, plot=False, 
               logscale=False, x=0.5, y=0.5).get_image()

qv3 = sphviewer.tools.QuickView(pos, np.ones_like(pos[:, 0]), r='infinity', hsml=hsml, xsize=1500, ysize=1500, plot=False,
               logscale=False, x=0.5, y=0.5).get_image() 

si = scatter_image(pos, np.ones_like(pos[:, 0]), np.array([0, 0, 0]), np.array([1, 1, 1]),
                   res_x=100, res_y=100, hsml=hsml,).T
si2 = scatter_image(pos, np.ones_like(pos[:, 0]), np.array([0, 0, 0]), np.array([1, 1, 1]),
                   res_x=500, res_y=500, hsml=hsml,).T
si3 = scatter_image(pos, np.ones_like(pos[:, 0]), np.array([0, 0, 0]), np.array([1, 1, 1]),
                   res_x=1500, res_y=1500, hsml=hsml,).T

fig, axes = plt.subplots(3, 3, figsize=(15, 15), dpi=300)

# Plot the results straight out of quickview
axes[0, 0].imshow(np.log10(qv + 1e-12), vmin=3.5, vmax=4.7, extent=[0, 1, 0, 1])
axes[0, 0].annotate("QuickView.get_image()", (0.05, 0.9), color="white",  fontsize=13)
axes[0, 0].annotate("100x100", (0.75, 0.05), color="white",  fontsize=13)

axes[0, 1].imshow(np.log10(qv2 + 1e-12), vmin=3.5, vmax=4.7, extent=[0, 1, 0, 1])
axes[0, 1].annotate("500x500", (0.75, 0.05), color="white",  fontsize=13)

axes[0, 2].imshow(np.log10(qv3 + 1e-12), vmin=3.5, vmax=4.7, extent=[0, 1, 0, 1])
axes[0, 2].annotate("1500x1500", (0.75, 0.05), color="white",  fontsize=13)

# Plot the results out of quickview, but normalise by the area of the pixel
axes[1, 0].imshow(np.log10(qv/(1/100)**2 + 1e-12), vmin=3.5, vmax=4.7, extent=[0, 1, 0, 1])
axes[1, 0].annotate("QuickView.get_image() / pixel_area", (0.05, 0.9), color="white", fontsize=13)

axes[1, 1].imshow(np.log10(qv2/(1/500)**2 + 1e-12), vmin=3.5, vmax=4.7)
axes[1, 2].imshow(np.log10(qv3/(1/1500)**2 + 1e-12), vmin=3.5, vmax=4.7)


# Plot the results out of trivial sph deposit
axes[2, 0].imshow(np.log10(si + 1e-12), vmin=3.5, vmax=4.7, extent=[0, 1, 0, 1])
axes[2, 0].annotate("Basic SPH deposit", (0.05, 0.9), color="white", fontsize=13)

axes[2, 1].imshow(np.log10(si2 + 1e-12), vmin=3.5, vmax=4.7)

axes[2, 2].imshow(np.log10(si3 + 1e-12), vmin=3.5, vmax=4.7)

for ax in axes.flatten():
    ax.set_xticklabels([])
    ax.set_yticklabels([])

plt.tight_layout()
plt.savefig("resolution_test.png", dpi=300)
plt.show()
```

returns,
![resolution_test](https://user-images.githubusercontent.com/30047498/66057272-57753200-e530-11e9-8751-31c988d7e61b.png)

so sphviewer agrees with a basic SPH smoothing function I wrote. But, it explicitly says in the `README.md` that for version 1.1.0, or above, 

"Image returned by Render.get_image(), or QuickView.get_image() is normalized by the pixel area. This means that the value of each pixel, when smoothing the particle mass, can be regarded as the actual surface density."

which is what caused me confusion, as that isn't true. You still need to divide by the pixel area to get the true surface density!

**Comment by AshKelly** [comment]
I think either the README should change to make it clear that the image is NOT the surface density, or the behavior should change to normalise by the pixel size so that it does return the physical surface density.

For reference, `sphviewer.__version__` yields `1.2.0` in my environment.

**Comment by JBorrow** [comment]
There is also some clear problem at very low resolutions. I believe me and Alejandro talked about this at some point... I will see if I can fix this.

**Comment by JBorrow** [comment]
Ok, I've fixed the problem with the weird low-resolution images, and will submit it as a MR:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/7839515/66090961-7a0c4880-e53a-11e9-9304-00d47e3f4fab.png">

We really should simultaneously fix the issue with the surface areas, though.

**Comment by JBorrow** [comment]
Ok, I now have four open MRs (sorry Alejandro) that fix all of these issues, as well as some compilation/code structure issues I found along the way.

**Comment by alejandrobll** [comment]
Surface density issue has been addressed and fixed. So, image is now always divided by the pixel area.

**Comment by JBorrow** [comment]
You may wish to 'close' this issue now
