### ISSUE TITLE
spy-viewer does not install on mac osx 10.8.5

### ISSUE THREAD

**Issue by HermenB** [alejandrobll/py-sphviewer#2]
Hi, I've tries all the installation options as described on the main page (pip install, git build-it-yourself) but I didn't succeed. A long list of errors is generated, of which I shall include the main ones below. But the part that struck me most was one of the first lines: 
         "creating build/lib.macosx-10.5-x86_64-2.7"
while I have 10.8. Are you sure this should work on modern iMacs?

I hope you can help. If needed, I can send you the complete log file from the installation.

Kind regards,

Hermen

Some snippets from the log-file:
...
fatal error: 'omp.h' file not found
Failed building wheel for py-sphviewer
  Running setup.py bdist_wheel for pykdtree
…
In file included from /Users/hermen/anaconda/envs/sph/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1728:
  /Users/hermen/anaconda/envs/sph/lib/python2.7/site-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
…
35 warnings generated.
…
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'gcc' failed with exit status 1

**Comment by alejandrobll** [comment]
Hi Hermen,
I have not a Mac right now to test it. However, after reading your error, it seems that your problem is that omp.h is missing. Are you sure you have it installed in your system? Could you please check that?

**Comment by HermenB** [comment]
Hi Alejandro,
Thank you for your response. Indeed it seems that omp.h is missing, I cannot find it anywhere on my system. Is there a way to install it separately? And, what is it exactly and where should it go?

Kind regards,

Hermen

**Comment by alejandrobll** [comment]
Hermen, OpenMP is used to do the parallel computation in shared-memory systems. I am not familiar with osx 10.8.5, you can probably try to install command line tools from apple. Otherwise, you should google how to get OpenMP installed.

**Comment by HermenB** [comment]
OK, thanks, I'll check into that.
kind regards,

Hermen

**Comment by alejandrobll** [comment]
You can also try updating the gcc compiler. 
Please, let me know if you succeed, and in such a case I would be glad to read the solution.
Regards,
Alejandro

**Comment by alejandrobll** [comment]
This problem seems related to mac osx 10.8.5 OS, so that I will close the issue.

**Comment by HermenB** [comment]
OK, I haven't had time to look into openmp yet, I will probably do an OS
update first.

Meanwhile, I have one suggestion. I was really impressed with the
cosmological example renders on the github page.
I was wondering if you could provide one (or more) of those datasets,
because much of the beauty of the final render lies in the particle
distribution.
If I manage to install sph-viewer, I'll let you know.
kind regards,

Hermen
