### ISSUE TITLE
Projections in different planes

### ISSUE THREAD

**Issue by Anikbh11** [alejandrobll/py-sphviewer#23]
Hi, 

I'm trying to make projections of sightlines projected along the z axis and hence the projections need to be in the xz plane. How do I change the plane of projection? I see there are options to plot the Particles and Camera in different planes but I'm quite confused as to how do I render a scene in a different plane. 

Thanks!

**Comment by alejandrobll** [comment]
Hi,
if particle positions are P[:,3], with P[:,0] = x, P[:,1] = y and P[:,2] = z, the `Scene` will collapse everything on the `x-y` plane. The plane of the projection can be changed by rotating the Camera by 90 degrees. This is done by calling `Scene.update_camera(t=90)`. `t` refers to the angle theta, which rotates respect to the x-axis. If you need to rotate around the y-axis, use `p`. And finally, to rotate around the z-axis, use `roll`. 

Another approach is redefining your particles array, but I guess you don't want to do that.

Cheers,
Alejandro

**Comment by Anikbh11** [comment]
Thanks a lot! I appreciate the help. 

Kind Regards,
Aniket
