### ISSUE TITLE
What do colors of image refer to?

### ISSUE THREAD

**Issue by WangYun1995** [alejandrobll/py-sphviewer#26]
Hi, @alejandrobll 

I find that many figures on display have no colorbar, so that I don't know colors of these images refer to what.
For example,  you said that this figure below shows the resulting density field. Does this "density" refer to mass density or number density? And what is the unit of this density field? 

![Screenshot](https://user-images.githubusercontent.com/68187127/109531709-3765eb80-7af3-11eb-834a-b88c752a3464.png)

**Comment by alejandrobll** [comment]
Hi @WangYun1995,
It is the surface density field for the chosen property. If you use sphviewer to spread the mass, say, you obtain the integral of the density along the line-of-sight, i.e., the column (or surface) density. If the unit of mass is in grams, and the length is in cm, the colour represents g/cm^2.

**Comment by WangYun1995** [comment]
Thank you for your reply.
