### ISSUE TITLE
hsv colormap tutorial

### ISSUE THREAD

**Issue by sshlpe** [alejandrobll/py-sphviewer#30]
Hi, i'm trying to create a plot like the one in your gallery but i cant figure out how do make a 2D colormap that shows 2 different features at ones. I was hoping you had an example of how did you make the hsv_sigma2_density2 image.

**Comment by alejandrobll** [comment]
There is one here:

http://alejandrobll.github.io/py-sphviewer/content/talks/talk_virgo.html

**Comment by sshlpe** [comment]
Amazing, thanks, tho i can't find the sphviewer_cbar module.
