### ISSUE TITLE
Speed up code with GPU?

### ISSUE THREAD

**Issue by sj-wilkinson** [alejandrobll/py-sphviewer#31]
Hi there. 

I'm regularly using this code to generate thousands of images and the computation time is a limiting factor and requires significant resources. Does Scene() or Render() support GPU processing? Would using a GPU help? Any other suggestions for speeding up the code in general? 

Thanks very much.

**Comment by alejandrobll** [comment]
Dear Scott,
I am glad to know that the code is helpful for you. There is a
GPU-accelerated version, but unfortunately, it is not yet publicly
available. If you have access to a computer cluster, you could speed up
your jobs by splitting the image into small chunks using MPI. Please check
the last part of this link, where I briefly explain the idea:
http://alejandrobll.github.io/py-sphviewer/content/talks/talk_virgo.html

Cheers,
Alejandro.
