### ISSUE TITLE
Render.get_image() units

### ISSUE THREAD

**Issue by sj-wilkinson** [alejandrobll/py-sphviewer#32]
Hi there, 

I saw the previous post here asking about the units of the final image, but still could use some clarification. If my input mass is in units of solar masses, is the image a surface density in solar masses per pixel area?

For some reason, the sum of the image output is larger in a smaller FOV cutout than a larger one and neither seem particularly close to the total mass of the halo found in the catalogues (IllustrisTNG100-1). 

Thanks very much for your time. 

Scott

**Comment by alejandrobll** [comment]
Hi,
are you using "r=infinity" for the camera? If so, the units should be given
by the gas particle mass and the extent parameters.

Cheers,
Alejandro.

**Comment by sj-wilkinson** [comment]
Hi Alejandro, 

Thanks for the response. By this do you mean that the units of the pixel values in the output image are in Msun/kpc^2, as per the input mass and extent parameters?

Thanks,
Scott

**Comment by alejandrobll** [comment]
Hi Scott,
Indeed, provided r='infinity' in the camera parameters.
