### ISSUE TITLE
Installation of py-sphviewer for python on windows 7 fails

### ISSUE THREAD

**Issue by adis1987** [alejandrobll/py-sphviewer#4]
It should be simple: pip install py-sphviewer

But the installation fails:

> Command ""c:\program files (x86)\python\python35-32\python.exe" -u -c "import setuptools, tokenize;**file**='C:\Users\Adis\AppData\Local\Temp\pip-build-t933z7vh\pykdtree\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\Adis\AppData\Local\Temp\pip-766djyup-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Adis\AppData\Local\Temp\pip-build-t933z7vh\pykdtree\

Im running Python 3.5.2 (x86)
Windows 7 (64-bit)

**Comment by alejandrobll** [comment]
It seems that there is an error when compiling pykdtree? Could you send the full log file of the error? Are you using Anaconda? Also,  py-sphviewer was written to be compatible with python 2.7 so in principle it won't work with 3.x

**Comment by adis1987** [comment]
[test.txt](https://github.com/alejandrobll/py-sphviewer/files/366689/test.txt)

There is the whole log.

**Comment by alejandrobll** [comment]
thanks. Yes, I can confirm that it is a problem with the py-kdtree installation. It happens because it doesn't recognize your system, in the line 33 of setup.py of [py-kdtree](https://github.com/alejandrobll/pykdtree/blob/master/setup.py) :

```
    if comp in ('unix', 'cygwin', 'mingw32')
```

You should add your system, then install it by your self, and the run again pip install py-sphviewer...  

This is nothing to do with py-sphviewer, but with an external dependency and your particular system.

**Comment by adis1987** [comment]
thanks!

**Comment by laserchaseman** [comment]
Do plan on making py-sohviewer compatible with python 3.x? I am using anaconda and wanted to use this with my current project that is in 3.5.

**Comment by alejandrobll** [comment]
It would be nice to know what parts need to be changed. I have no much time right now, and also I am not familiar with Python 3.x, but if the changes are not huge I would be able to do so. Feel free to rise a new issue and suggest the changes.

**Comment by cuixh0324** [comment]
I have same error cant install it. I have try to add my computer type in The line but failed.
C:\Users\Administrator>cd C:\Users\Administrator\Desktop\pykdtree-1.2.2\pykdtree
-1.2.2

C:\Users\Administrator\Desktop\pykdtree-1.2.2\pykdtree-1.2.2> python setup.py in
stall
running install
running bdist_egg
running egg_info
writing requirements to pykdtree.egg-info\requires.txt
writing pykdtree.egg-info\PKG-INFO
writing top-level names to pykdtree.egg-info\top_level.txt
writing dependency_links to pykdtree.egg-info\dependency_links.txt
reading manifest file 'pykdtree.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'pykdtree\render_template.p
y'
writing manifest file 'pykdtree.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
this is my computer type: msvc
building 'pykdtree.kdtree' extension
C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Py
thon\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -ID:\Anaconda2
\include -ID:\Anaconda2\PC -ID:\Anaconda2\lib\site-packages\numpy\core\include /
Tcpykdtree/kdtree.c /Fobuild\temp.win-amd64-2.7\Release\pykdtree/kdtree.obj /Ox
/openmp
kdtree.c
d:\anaconda2\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h
(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_D
EPRECATED_API NPY_1_7_API_VERSION
pykdtree/kdtree.c(354) : fatal error C1083: Cannot open include file: 'stdint.h'
: No such file or directory
error: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Micr
osoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit stat
us 2

C:\Users\Administrator\Desktop\pykdtree-1.2.2\pykdtree-1.2.2>

**Comment by alejandrobll** [comment]
@cuixh0324 , this is a problem with py-kdtree rather than with py-sphviewer. From your log file, it seems that stdint.h is missing. Try with this [post](https://stackoverflow.com/questions/12970293/why-microsoft-visual-studio-cannot-find-stdint-h/12970619#12970619).
