### ISSUE TITLE
Please add python 3 support

### ISSUE THREAD

**Issue by jsmidt** [alejandrobll/py-sphviewer#8]
This package is wonderful, but only seems to work with Python 2. Given [Python 2 is retiring in about 2.5 years](https://pythonclock.org/), it would be nice if this package made that transition.

**Comment by alejandrobll** [comment]
Thanks for your comment. I agree that it would be nice if the package also work with Python 3, and suspect that it may work with very minor changes. I will take your comment seriously and will start to dig into which parts need to be changed so that I can ensure full compatibility with Python 3.

**Comment by alejandrobll** [comment]
There are currently some incompatibilities arising from pykdtree. Unless this is fixed first, I cannot make much progress on this.

**Comment by alejandrobll** [comment]
Any help in changing what need to be changed so that the code is Python 3 compatible is more than welcome.
